api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: 80
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.OCTOPETS_APPINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
  template:
    containers:
      - image: {{ .Image }}
        name: octopetsfe
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: services__octopetsapi__http__0
            value: http://octopetsapi.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__octopetsapi__https__0
            value: https://octopetsapi.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            secretRef: applicationinsights-connection-string
    scale:
      minReplicas: 1
tags:
  azd-service-name: octopetsfe
  aspire-resource-name: octopetsfe
